from pygame.image import load
from tools import load_images
from .paths import (
    BACKGROUND_STATIC_PATHS,
    BACKGROUND_SCROLL_PATHS,
    DUCK_MIDDLE_IDLE_PATHS,
    DUCK_IDLE_PATHS,
    DUCK_WALKING_PATHS,
    DUCK_RUNNING_PATHS,
    DUCK_CROUCHING_PATHS,
    DUCK_JUMPING_PATH,
    DUCK_CROUCHING_IDLE_PATH,
    DUCK_RUDE_PATH,
    DUCK_DEAD_PATH,
    SLIME_WALKING_PATH,
    SLIME_DEATH_PATH,
    ROYAL_SCARAB_WALKING_PATH,
    GIANT_ROYAL_SCARAB_WALKING_PATH,
    RED_BRICK_PATH,
    GREY_BRICK_PATH,
    STONE_PATH,
    COIN_PATHS,
    DIAMOND_PATHS,
    START_BUTTON_PATHS,
    SETTINGS_BUTTON_PATHS,
    QUIT_BUTTON_PATHS,
    BEE_FLYING_PATHS,
    BEE_DEATH_PATHS
)

BACKGROUND_STATIC_IMAGES = load_images(BACKGROUND_STATIC_PATHS)
BACKGROUND_SCROLL_IMAGES = load_images(BACKGROUND_SCROLL_PATHS)

DUCK_MIDDLE_IDLE_IMAGES = load_images(DUCK_MIDDLE_IDLE_PATHS)
DUCK_IDLE_IMAGES = load_images(DUCK_IDLE_PATHS)
DUCK_WALKING_IMAGES = load_images(DUCK_WALKING_PATHS)
DUCK_RUNNING_IMAGES = load_images(DUCK_RUNNING_PATHS)
DUCK_CROUCHING_IMAGES = load_images(DUCK_CROUCHING_PATHS)
DUCK_JUMPING_IMAGE = load(DUCK_JUMPING_PATH)
DUCK_CROUCHING_IDLE_IMAGE = load(DUCK_CROUCHING_IDLE_PATH)
DUCK_RUDE_IMAGE = load(DUCK_RUDE_PATH)
DUCK_DEAD_IMAGE = load(DUCK_DEAD_PATH)

SLIME_WALKING_IMAGES = load_images(SLIME_WALKING_PATH)
SLIME_DEATH_IMAGES = load_images(SLIME_DEATH_PATH)

ROYAL_SCARAB_WALKING_IMAGES = load_images(ROYAL_SCARAB_WALKING_PATH)
GIANT_ROYAL_SCARAB_WALKING_IMAGES = load_images(GIANT_ROYAL_SCARAB_WALKING_PATH)

RED_BRICK_IMAGE = load(RED_BRICK_PATH)
GREY_BRICK_IMAGE = load(GREY_BRICK_PATH)
STONE_IMAGE = load(STONE_PATH)

COIN_IMAGES = load_images(COIN_PATHS)
DIAMOND_IMAGES = load_images(DIAMOND_PATHS)

START_BUTTON_IMAGES = load_images(START_BUTTON_PATHS)
SETTINGS_BUTTON_IMAGES = load_images(SETTINGS_BUTTON_PATHS)
QUIT_BUTTON_IMAGES = load_images(QUIT_BUTTON_PATHS)

GAME_ICON_IMAGE = DUCK_IDLE_IMAGES[0]

BEE_FLYING_IMAGES = load_images(BEE_FLYING_PATHS)
BEE_DEATH_IMAGES = load_images(BEE_DEATH_PATHS)